spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/applciation-storage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  locations: classpath:migration
  baseline-on-migrate: true
